// Objective-C API for talking to Share-Wallet/cmd/wallet-sdk-core/hot-wallet Go package.
//   gobind -lang=objc Share-Wallet/cmd/wallet-sdk-core/hot-wallet
//
// File is generated by gobind. Do not edit.

#ifndef __Hot_wallet_H__
#define __Hot_wallet_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT BOOL Hot_walletCheckUserWallet(NSString* _Nullable userID);

/**
 * fetch the specific coin address of the friend
 */
FOUNDATION_EXPORT NSString* _Nonnull Hot_walletFetchFriendAddress(NSString* _Nullable userID, int64_t coinType);

/**
 * *
coinType: 1 BTC, 2 ETH, 3 USDT-ERC20, 4 TRX, 5 USDT-TRC20
 */
FOUNDATION_EXPORT NSString* _Nonnull Hot_walletGetBalance(long coinType, NSString* _Nullable publicAddress);

FOUNDATION_EXPORT NSString* _Nonnull Hot_walletGetCoinRatio(void);

FOUNDATION_EXPORT BOOL Hot_walletGetCoinStatuses(void);

FOUNDATION_EXPORT NSString* _Nonnull Hot_walletGetConfirmation(long coinType, NSString* _Nullable transactionHash);

/**
 * only for ETH, USDT-ERC20
 */
FOUNDATION_EXPORT NSString* _Nonnull Hot_walletGetGasPrice(long coinType);

FOUNDATION_EXPORT NSString* _Nonnull Hot_walletGetPublicAddress(long coinType);

FOUNDATION_EXPORT NSString* _Nonnull Hot_walletGetRecentTransactions(long page, long pageSize);

FOUNDATION_EXPORT NSString* _Nonnull Hot_walletGetTransaction(long coinType, NSString* _Nullable publicAddress, NSString* _Nullable transactionHash);

FOUNDATION_EXPORT NSString* _Nonnull Hot_walletGetTransactionFee(int64_t coinType, double gasPrice);

FOUNDATION_EXPORT NSString* _Nonnull Hot_walletGetTransactionList(long coinType, NSString* _Nullable publicAddress, long transactionType, long page, long pageSize, NSString* _Nullable orderBy);

FOUNDATION_EXPORT NSString* _Nonnull Hot_walletTestHot(void);

FOUNDATION_EXPORT NSString* _Nonnull Hot_walletTransfer(long coinType, NSString* _Nullable fromAddress, NSString* _Nullable toAddress, NSString* _Nullable secret, double amount, double gasPrice, NSError* _Nullable* _Nullable error);

#endif
