
// Objective-C API for talking to the following Go packages
//
//	Share-Wallet/cmd/wallet-sdk-core/cold-wallet
//	Share-Wallet/cmd/wallet-sdk-core/hot-wallet
//
// File is generated by gomobile bind. Do not edit.
#ifndef __WalletSdkCore_FRAMEWORK_H__
#define __WalletSdkCore_FRAMEWORK_H__

#include "Cold_wallet.objc.h"
#include "Hot_wallet.objc.h"
#include "Universe.objc.h"

#endif
